# The west manifest file (west.yml) for the nRF Connect SDK (NCS).
#
# The per-workspace west configuration file, ncs/.west/config,
# specifies the location of this manifest file like this:
#
#     [manifest]
#     path = nrf
#
# See the west documentation for more information:
#
# https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/guides/west/index.html

manifest:
  version: "0.12"

  # "remotes" is a list of locations where git repositories are cloned
  # and fetched from.
  remotes:
    # nRF Connect SDK GitHub organization.
    # NCS repositories are hosted here.
    - name: ncs
      url-base: https://github.com/nrfconnect
    # Third-party repository sources:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: throwtheswitch
      url-base: https://github.com/ThrowTheSwitch
    - name: armmbed
      url-base: https://github.com/ARMmbed
    - name: nordicsemi
      url-base: https://github.com/NordicSemiconductor
    - name: memfault
      url-base: https://github.com/memfault

  # If not otherwise specified, the projects below should be obtained
  # from the ncs remote.
  defaults:
    remote: ncs

  group-filter: [-homekit, -nrf-802154, -find-my, -doc-internal]

  # "projects" is a list of git repositories which make up the NCS
  # source code.
  projects:

    # The Zephyr RTOS fork in the NCS, along with the subset of its
    # modules which NCS imports directly.
    #
    # https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/introduction/index.html
    # https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/guides/modules.html
    - name: zephyr
      repo-path: sdk-zephyr-next
      revision: 4260292cbf5cc2e24325e46836fe1323e350fb5c
      import:
        # In addition to the zephyr repository itself, NCS also
        # imports the contents of zephyr/west.yml at the above
        # revision. Only the projects explicitly named in the
        # following allowlist are imported.
        #
        # Note that the zephyr west extensions (like 'build', 'flash',
        # 'debug', etc.) are automatically provided by this import, so
        # there's no need to add a redundant west-commands: key for
        # the zephyr project.
        #
        # Please keep this list sorted alphabetically.
        name-allowlist:
          - TraceRecorderSource
          - canopennode
          - chre
          - cmsis
          - coremark
          - edtt
          - fatfs
          - fff
          - hal_st
          - liblc3codec
          - libmetal
          - littlefs
          - loramac-node
          - lvgl
          - lz4
          - mbedtls
          - mipi-sys-t
          - nanopb
          - net-tools
          - nrf_hw_models
          - open-amp
          - picolibc
          - psa-arch-tests
          - sdk-hal_nordic-next
          - segger
          - tinycbor
          - tinycrypt
          - tf-m-tests
          - zcbor
          - zscilib

    # NCS repositories.
    #
    # Some of these are also Zephyr modules which have NCS-specific
    # changes.
    - name: sdk-hostap
      path: modules/lib/hostap
      revision: 47399f055431513b5dfcd9d1fd1ec5dc5c96a252
    - name: mcuboot
      repo-path: sdk-mcuboot
      revision: v1.9.99-ncs2
      path: bootloader/mcuboot
    - name: mbedtls-nrf
      path: mbedtls
      repo-path: sdk-mbedtls
      revision: v3.1.0-ncs1
    - name: nrfxlib
      repo-path: sdk-nrfxlib-next
      path: nrfxlib
      revision: 83357864cefcd877152f8470c3ac795ea5bfa92f
    - name: doc-internal
      repo-path: doc-internal
      path: modules/doc-internal
      revision: 847c13b4f61753f8c5162b94c5e7628632a1fe74
      groups:
      - doc-internal
    - name: ic-next
      repo-path: sdk-ic-next
      path: modules/ic-next
      revision: 399af071ee10a5c5194bdcce81ea4632e4228a0f
    - name: sdk-secdom
      revision: 95f89ad795aa0dd4c37f2b027ebab21e69c29453
      path: core_fw/secdom
    - name: nrf-regtool
      revision: c5d464268b0fe3657028c9994516979fbcbf3885
      path: modules/lib/nrf-regtool
    - name: nrfs
      path: modules/lib/nrfs
      revision: b4ae806d5ec4e5bffeca0a91b38c8ee742b0b497
    - name: sdk-sysctrl
      revision: 0fc6e23f2e0f5b24b45b792b7f2a0e5d3f4d644d
      path: core_fw/sysctrl
    - name: trusted-firmware-m
      repo-path: sdk-trusted-firmware-m
      path: modules/tee/tf-m/trusted-firmware-m
      revision: v1.6.0-ncs1
    - name: tfm-mcuboot # This is used by the trusted-firmware-m module.
      repo-path: sdk-mcuboot
      path: modules/tee/tfm-mcuboot
      revision: v1.7.2-ncs2
    - name: matter
      repo-path: sdk-connectedhomeip-next
      path: modules/lib/matter
      revision: 84bb9ce7bfa41c25a0a57b3f38ebefdd3ed3fb57
      submodules:
        - name: nlio
          path: third_party/nlio/repo
        - name: nlassert
          path: third_party/nlassert/repo
        - name: nlunit-test
          path: third_party/nlunit-test/repo
        - name: pigweed
          path: third_party/pigweed/repo
    - name: nrf-802154
      repo-path: sdk-nrf-802154
      path: nrf-802154
      revision: v2.1.0
      groups:
      - nrf-802154
    - name: cjson
      repo-path: sdk-cjson
      path: modules/lib/cjson
      revision: c6af068b7f05207b28d68880740e4b9ec1e4b50a
    - name: homekit
      repo-path: sdk-homekit
      revision: v2.1.0
      groups:
      - homekit
    - name: find-my
      repo-path: sdk-find-my
      revision: v2.1.0
      groups:
      - find-my
    - name: azure-sdk-for-c
      repo-path: azure-sdk-for-c
      path: modules/lib/azure-sdk-for-c
      revision: 308c171cb4b5eed266649012a68406487ec81fb2
    - name: suit-processor
      remote: nordicsemi
      revision: f98aacffd3834bcaba66811f532c270c0f4de2d5
      path: modules/lib/suit-processor
    # Other third-party repositories.
    - name: cmock
      path: test/cmock
      submodules: true
      revision: f65066f15d8248e6dcb778efb8739904a4512087
      remote: throwtheswitch
    - name: memfault-firmware-sdk
      path: modules/lib/memfault-firmware-sdk
      revision: 0.33.2
      remote: memfault
    - name: cirrus
      repo-path: sdk-mcu-drivers
      path: modules/hal/cirrus-logic
      revision: 9f6b3812237fbb0d4157ba3584c13f1644fcbe3a
    - name: openthread
      repo-path: sdk-openthread
      path: modules/lib/openthread
      revision: 488ee63b4c170cb5d1789258a69f27aba19c3720

  # West-related configuration for the nrf repository.
  self:
    # This repository should be cloned to ncs/nrf.
    path: nrf
    # This line configures west extensions.
    west-commands: scripts/west-commands.yml
