# The west manifest file (west.yml) for the nRF Connect SDK (NCS).
#
# The per-workspace west configuration file, ncs/.west/config,
# specifies the location of this manifest file like this:
#
#     [manifest]
#     path = nrf
#
# See the west documentation for more information:
#
# https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/guides/west/index.html

manifest:
  version: "0.13"

  # "remotes" is a list of locations where git repositories are cloned
  # and fetched from.
  remotes:
    # nRF Connect SDK GitHub organization.
    # NCS repositories are hosted here.
    - name: ncs
      url-base: https://github.com/nrfconnect
    # Third-party repository sources:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: throwtheswitch
      url-base: https://github.com/ThrowTheSwitch
    - name: armmbed
      url-base: https://github.com/ARMmbed
    - name: nordicsemi
      url-base: https://github.com/NordicSemiconductor
    - name: dragoon
      url-base: https://projecttools.nordicsemi.no/bitbucket/scm/drgn
    - name: memfault
      url-base: https://github.com/memfault
    - name: ant-nrfconnect
      url-base: https://github.com/ant-nrfconnect

  # If not otherwise specified, the projects below should be obtained
  # from the ncs remote.
  defaults:
    remote: ncs

  group-filter: [-homekit, -nrf-802154, -dragoon, -find-my, -doc-internal]

  # "projects" is a list of git repositories which make up the NCS
  # source code.
  #
  # For 'userdata' fields in the projects area, please refer to:
  # https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/dm_code_base.html
  projects:

    # The Zephyr RTOS fork in the NCS, along with the subset of its
    # modules which NCS imports directly.
    #
    # https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/introduction/index.html
    # https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/guides/modules.html
    - name: zephyr
      repo-path: sdk-zephyr-next
      revision: aa27dbbb6fe16d5a589a3b7f9707dc8e3815b760
      import:
        # In addition to the zephyr repository itself, NCS also
        # imports the contents of zephyr/west.yml at the above
        # revision. Only the projects explicitly named in the
        # following allowlist are imported.
        #
        # Note that the zephyr west extensions (like 'build', 'flash',
        # 'debug', etc.) are automatically provided by this import, so
        # there's no need to add a redundant west-commands: key for
        # the zephyr project.
        #
        # Please keep this list sorted alphabetically.
        name-allowlist:
          - TraceRecorderSource
          - canopennode
          - chre
          - cmsis
          - coremark
          - edtt
          - fatfs
          - fff
          - hal_st
          - liblc3codec
          - libmetal
          - littlefs
          - loramac-node
          - lvgl
          - lz4
          - mipi-sys-t
          - nanopb
          - net-tools
          - nrf_hw_models
          - open-amp
          - picolibc
          - psa-arch-tests
          - sdk-hal_nordic-next
          - segger
          - tinycbor
          - tinycrypt
          - tf-m-tests
          - uoscore-uedhoc
          - zcbor
          - zscilib

    # NCS repositories.
    #
    # Some of these are also Zephyr modules which have NCS-specific
    # changes.
    - name: sdk-hostap
      path: modules/lib/hostap
      revision: c1f1e0593d5bde73ba5d512b44fb765472829574
    - name: mcuboot
      repo-path: sdk-mcuboot
      revision: 9d2f9b5742c5cabcb87b7f7f22ff5269b13403bf
      path: bootloader/mcuboot
    - name: mbedtls-nrf
      path: mbedtls
      repo-path: sdk-mbedtls
      revision: v3.1.0-ncs2
    - name: nrfxlib
      repo-path: sdk-nrfxlib-next
      path: nrfxlib
      revision: 5d7eaac546703af8d214383b2b002784d990edcf
    - name: doc-internal
      repo-path: doc-internal
      path: modules/doc-internal
      revision: 7e505f7da3da55bf8163a225556def5b0254745b
      groups:
      - doc-internal
    - name: ic-next
      repo-path: sdk-ic-next
      path: modules/ic-next
      revision: 62c405fb8635eab2935b8de335bc7bc53f0d2c3d
    - name: sdk-secdom
      revision: f82680daeb73cc7008393ea927a72bc3dc2da185
      path: core_fw/secdom
    - name: nrf-regtool
      revision: 72a88481d00d772585bd7a7c325916acc645e5c1
      path: modules/lib/nrf-regtool
    - name: nrfs
      path: modules/lib/nrfs
      revision: 8720c48205798282ddccf8f0b3e7093d28fca9ea
    - name: sdk-sysctrl
      revision: 6c7e4a870b188d4b93606a012339ca18a9cf3521
      path: core_fw/sysctrl
    - name: trusted-firmware-m
      repo-path: sdk-trusted-firmware-m
      path: modules/tee/tf-m/trusted-firmware-m
      revision: 1b7ee9d3cb09cb0081f49c3d20220cdf7d5f7b3c
    - name: matter
      repo-path: sdk-connectedhomeip-next
      path: modules/lib/matter
      revision: 39436db7a196caa3c41e348cc5aa558b239c6c3a
      submodules:
        - name: nlio
          path: third_party/nlio/repo
        - name: nlassert
          path: third_party/nlassert/repo
        - name: nlunit-test
          path: third_party/nlunit-test/repo
        - name: pigweed
          path: third_party/pigweed/repo
    - name: nrf-802154
      repo-path: sdk-nrf-802154
      path: nrf-802154
      revision: c601469f41ecc4546cd1feb04d49b611cc872161
      groups:
        - nrf-802154
    - name: dragoon
      # Only for internal Nordic development
      repo-path: dragoon.git
      remote: dragoon
      revision: b093384fc4663a2da582811314e13db2a52c81ac
      submodules: true
      groups:
        - dragoon
    - name: cjson
      repo-path: sdk-cjson
      path: modules/lib/cjson
      revision: c6af068b7f05207b28d68880740e4b9ec1e4b50a
    - name: homekit
      repo-path: sdk-homekit
      revision: 4a941dc22638852f841aa9644aaeb72f9c95cfea
      groups:
        - homekit
    - name: find-my
      repo-path: sdk-find-my
      revision: 219987daaac52ff0799ca29aaf7aff5f1276f045
      groups:
        - find-my
    - name: azure-sdk-for-c
      repo-path: azure-sdk-for-c
      path: modules/lib/azure-sdk-for-c
      revision: 308c171cb4b5eed266649012a68406487ec81fb2
    - name: suit-processor
      revision: c2b3d445f82be95a56b18df5269ed801abb70f50
      path: modules/lib/suit-processor
    - name: suit-generator
      revision: fd39ab8825d26d6365f604e5c942627228873b34
      path: modules/lib/suit-generator
    # Other third-party repositories.
    - name: cmock
      path: test/cmock
      submodules: true
      revision: f65066f15d8248e6dcb778efb8739904a4512087
      remote: throwtheswitch
    - name: memfault-firmware-sdk
      path: modules/lib/memfault-firmware-sdk
      revision: 0.35.0
      remote: memfault
    - name: cirrus
      repo-path: sdk-mcu-drivers
      path: modules/hal/cirrus-logic
      revision: 9f6b3812237fbb0d4157ba3584c13f1644fcbe3a
    - name: openthread
      repo-path: sdk-openthread
      path: modules/lib/openthread
      revision: 488ee63b4c170cb5d1789258a69f27aba19c3720

  # West-related configuration for the nrf repository.
  self:
    # This repository should be cloned to ncs/nrf.
    path: nrf
    # This line configures west extensions.
    west-commands: scripts/west-commands.yml
