# The west manifest file (west.yml) for the nRF Connect SDK (NCS).
#
# The per-workspace west configuration file, ncs/.west/config,
# specifies the location of this manifest file like this:
#
#     [manifest]
#     path = nrf
#
# See the west documentation for more information:
#
# https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/guides/west/index.html

manifest:
  version: "0.13"

  # "remotes" is a list of locations where git repositories are cloned
  # and fetched from.
  remotes:
    # nRF Connect SDK GitHub organization.
    # NCS repositories are hosted here.
    - name: ncs
      url-base: https://github.com/nrfconnect
    # Third-party repository sources:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: throwtheswitch
      url-base: https://github.com/ThrowTheSwitch
    - name: armmbed
      url-base: https://github.com/ARMmbed
    - name: nordicsemi
      url-base: https://github.com/NordicSemiconductor
    - name: dragoon
      url-base: https://projecttools.nordicsemi.no/bitbucket/scm/drgn
    - name: memfault
      url-base: https://github.com/memfault
    - name: ant-nrfconnect
      url-base: https://github.com/ant-nrfconnect
    - name: babblesim
      url-base: https://github.com/BabbleSim

  # If not otherwise specified, the projects below should be obtained
  # from the ncs remote.
  defaults:
    remote: ncs

  group-filter: [-nrf-802154, -dragoon, -find-my, -ant, -babblesim, -doc-internal]

  # "projects" is a list of git repositories which make up the NCS
  # source code.
  #
  # For 'userdata' fields in the projects area, please refer to:
  # https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/dm_code_base.html
  projects:

    # The Zephyr RTOS fork in the NCS, along with the subset of its
    # modules which NCS imports directly.
    #
    # https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/introduction/index.html
    # https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/guides/modules.html
    - name: zephyr
      repo-path: sdk-zephyr-next
      revision: bdffa556ec7eed08bbbb4e7c8cad72db67be9681
      import:
        # In addition to the zephyr repository itself, NCS also
        # imports the contents of zephyr/west.yml at the above
        # revision. Only the projects explicitly named in the
        # following allowlist are imported.
        #
        # Note that the zephyr west extensions (like 'build', 'flash',
        # 'debug', etc.) are automatically provided by this import, so
        # there's no need to add a redundant west-commands: key for
        # the zephyr project.
        #
        # Please keep this list sorted alphabetically.
        name-allowlist:
          - TraceRecorderSource
          - canopennode
          - chre
          - cmsis
          - coremark
          - edtt
          - fatfs
          - hal_st # required for ST sensors (unrelated to STM32 MCUs)
          - hal_wurthelektronik
          - liblc3
          - libmetal
          - littlefs
          - loramac-node
          - lvgl
          - lz4
          - mipi-sys-t
          - nanopb
          - net-tools
          - nrf_hw_models
          - open-amp
          - picolibc
          - sdk-hal_nordic-next
          - segger
          - tinycbor
          - tinycrypt
          - tf-m-tests
          - uoscore-uedhoc
          - zcbor
          - zscilib

    # NCS repositories.
    #
    # Some of these are also Zephyr modules which have NCS-specific
    # changes.
    - name: hostap
      repo-path: sdk-hostap
      path: modules/lib/hostap
      revision: ab0496ee9170bfe39535f8b501879be6bf8fbfbe
      userdata:
        ncs:
          upstream-url: https://w1.fi/cgit/hostap/
          upstream-sha: e792f38db8471f35ee94f109a4093dece8f78c6a
          compare-by-default: false
    - name: mcuboot
      repo-path: sdk-mcuboot
      revision: v1.10.0-ncs1
      path: bootloader/mcuboot
    - name: qcbor
      url: https://github.com/laurencelundblade/QCBOR.git
      revision: b0e7033268e88c9f27146fa9a1415ef4c19ebaff
      path: modules/tee/tf-m/qcbor
    - name: mbedtls
      path: modules/crypto/mbedtls
      repo-path: sdk-mbedtls
      revision: v3.3.0-ncs1
    - name: nrfxlib
      repo-path: sdk-nrfxlib-next
      path: nrfxlib
      revision: 8a70b48496880109097d7f2e85307a4821fa6907
    - name: doc-internal
      repo-path: doc-internal
      path: modules/doc-internal
      revision: 7540253ab539dd70eb2481d754c1de66c45c08d1
      groups:
      - doc-internal
    - name: ic-next
      repo-path: sdk-ic-next
      path: modules/ic-next
      revision: e679bfc6510dccfea6e9c8e27342a3b0ed7fdf43
    - name: sdk-secdom
      revision: 4baa688945bb136b1da45d5e7080458604ae21f4
      path: core_fw/secdom
    - name: nrf-regtool
      revision: v4.3.0
      path: modules/lib/nrf-regtool
    - name: nrfs
      path: modules/lib/nrfs
      revision: 8ab09c1ef1845d77617e2cf428e5e3dc748ce43b
    - name: sdk-sysctrl
      revision: 41b427706477dd539721c6416dacb185c7f5112f
      path: core_fw/sysctrl
    - name: trusted-firmware-m
      repo-path: sdk-trusted-firmware-m-next
      path: modules/tee/tf-m/trusted-firmware-m
      revision: 2ca0967ec4fe5e0d619cbfaacc80456d02089561
    - name: psa-arch-tests
      repo-path: sdk-psa-arch-tests
      path: modules/tee/tf-m/psa-arch-tests
      revision: 2102e16a0108cd903c8ac6b91e1d72f23b06479f
    - name: matter
      repo-path: sdk-connectedhomeip-next
      path: modules/lib/matter
      revision: bb33dab7df7f264e1f32d927f59b41deb9ae6eeb
      submodules:
        - name: nlio
          path: third_party/nlio/repo
        - name: nlassert
          path: third_party/nlassert/repo
        - name: nlunit-test
          path: third_party/nlunit-test/repo
        - name: pigweed
          path: third_party/pigweed/repo
      userdata:
        ncs:
          upstream-url: https://github.com/project-chip/connectedhomeip
          upstream-sha: 8f66f4215bc0708efc8cc73bda80620e67d8955f
          compare-by-default: false
      groups:
        - matter
    - name: nrf-802154
      repo-path: sdk-nrf-802154
      path: nrf-802154
      revision: e45bb47f0a4a43b69d19a145bdf15001d67e02dd
      groups:
        - nrf-802154
    - name: dragoon
      # Only for internal Nordic development
      repo-path: dragoon.git
      remote: dragoon
      revision: a79b463a3c62549c5cf6b3480d7d0ba63898eb8e
      submodules: true
      groups:
        - dragoon
    - name: cjson
      repo-path: sdk-cjson
      path: modules/lib/cjson
      revision: c6af068b7f05207b28d68880740e4b9ec1e4b50a
      userdata:
        ncs:
          upstream-url: https://github.com/DaveGamble/cJSON
          upstream-sha: d2735278ed1c2e4556f53a7a782063b31331dbf7
          compare-by-default: false
    - name: find-my
      repo-path: sdk-find-my-next
      revision: b3fb0e88cb6303864541b1f3783b15d8f046d906
      groups:
        - find-my
    - name: azure-sdk-for-c
      repo-path: azure-sdk-for-c
      path: modules/lib/azure-sdk-for-c
      revision: 308c171cb4b5eed266649012a68406487ec81fb2
      userdata:
        ncs:
          upstream-url: https://github.com/Azure/azure-sdk-for-c
          upstream-sha: adc56bc6138a28b5490bce339a31a2581a072092
          compare-by-default: false
    - name: cirrus
      repo-path: sdk-mcu-drivers
      path: modules/hal/cirrus-logic
      revision: 9f6b3812237fbb0d4157ba3584c13f1644fcbe3a
      userdata:
        ncs:
          upstream-url: https://github.com/CirrusLogic/mcu-drivers
          upstream-sha: 1be6ca7253133a21a1e9fe0fbb4656e17d63a936
          compare-by-default: false
    - name: openthread
      repo-path: sdk-openthread
      path: modules/lib/openthread
      revision: d9abe3071c0131a4adb5d7e7451319b735e6d855
      userdata:
        ncs:
          upstream-url: https://github.com/openthread/openthread
          upstream-sha: d9abe3071c0131a4adb5d7e7451319b735e6d855
          compare-by-default: false

    - name: suit-processor
      revision: 0aca81590efb46921b3006039f250b278d975eed
      path: modules/lib/suit-processor
    - name: suit-generator
      revision: 11f43f14215d6eb6b0610b5398af64e3fab5cfd0
      path: modules/lib/suit-generator
      groups:
        - suit-generator

    # Other third-party repositories.
    - name: cmock
      path: test/cmock
      submodules: true
      revision: f65066f15d8248e6dcb778efb8739904a4512087
      remote: throwtheswitch
    - name: memfault-firmware-sdk
      path: modules/lib/memfault-firmware-sdk
      revision: 0.43.3
      remote: memfault
    - name: ant
      repo-path: sdk-ant
      revision: 01087e4e6d2a9c4dec759ad6223d39e0cfb2bfa2
      remote: ant-nrfconnect
      groups:
        - ant
    - name: bsim
      repo-path: bsim_west
      remote: babblesim
      revision: 908ffde6298a937c6549dbfa843a62caab26bfc5
      import:
        path-prefix: tools


  # West-related configuration for the nrf repository.
  self:
    # This repository should be cloned to ncs/nrf.
    path: nrf
    # This line configures west extensions.
    west-commands: scripts/west-commands.yml
