[gpio_own_5]
PIN_0 = "Own"
PIN_1 = "Own"
PIN_2 = "Own"
PIN_3 = "Own"

[gpio_secure_5]
PIN_0 = "NonSecure"
PIN_1 = "NonSecure"
PIN_2 = "NonSecure"
PIN_3 = "NonSecure"

[gpiote_ch_secure_0]
CH_0 = "NonSecure"
CH_1 = "NonSecure"
CH_2 = "NonSecure"
CH_3 = "NonSecure"
