# This TOML configuration adds configurations for UICR that are currently
# unable to be set through devicetree.

[initnsvtor_0]
INITNSVTOR = 0x0e099000

[gpio_own_5]
PIN_0 = "Own"
PIN_1 = "Own"
PIN_2 = "Own"
PIN_3 = "Own"

[gpio_secure_5]
PIN_2 = "NonSecure"
PIN_3 = "NonSecure"
