[dppi_local_ch_secure_0]
CH_0 = "NonSecure"
CH_1 = "NonSecure"
CH_2 = "NonSecure"
CH_3 = "NonSecure"
CH_4 = "NonSecure"
CH_5 = "NonSecure"
CH_6 = "NonSecure"
CH_7 = "NonSecure"
CH_8 = "NonSecure"
CH_9 = "NonSecure"
CH_10 = "NonSecure"
CH_11 = "NonSecure"
CH_12 = "NonSecure"
CH_13 = "NonSecure"
CH_14 = "NonSecure"
CH_15 = "NonSecure"

[dppi_global_ch_secure_1]
CH_0 = "NonSecure"
CH_1 = "NonSecure"

[dppi_global_ch_secure_3]
CH_0 = "NonSecure"
CH_1 = "NonSecure"

[dppi_global_chg_secure_3]
CHG_0 = "NonSecure"
CHG_1 = "NonSecure"

[ipct_local_ch_secure_0]
CH_0 = "NonSecure"
CH_1 = "NonSecure"

[ipct_global_ch_secure_1]
CH_0 = "NonSecure"
CH_1 = "NonSecure"

[grtc_cc_secure_0]
CC_8 = "NonSecure"
CC_9 = "NonSecure"
CC_10 = "NonSecure"
CC_11 = "NonSecure"
