#
# Copyright (c) 2022 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# This TOML configuration adds configurations for UICR that are currently
# unable to be set through devicetree.

[initnsvtor_0]
INITNSVTOR = 0x0e054000
